//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Contact
    {
        public int ContactId { get; set; }
        [Required(ErrorMessage="The Subject field is required.")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Email Field is Reuired.")]
        public string Email { get; set; }
        [Required(), MinLength(25)]
        public string Message { get; set; }
    }
}
