//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class JobPost
    {
        public int JobId { get; set; }
        [Required(ErrorMessage = "Job Title field is required")]
        public string JobTitle { get; set; }
        [Required(ErrorMessage = "Job Description field is required.")]
        public string Description { get; set; }
        [Required(ErrorMessage = "Education field is required")]
        public string Education { get; set; }
        [Required(ErrorMessage = "Experience field is required")]
        public Nullable<decimal> Experience { get; set; }
        [Required(ErrorMessage = "Specialization field is required")]
        public string Specialization { get; set; }
        [Required(ErrorMessage = "Date field is requied.")]
        public string LastDate { get; set; }
        [Required(ErrorMessage = "Salary Field is required.")]
        public Nullable<decimal> Salary { get; set; }
        [Required(ErrorMessage = "Compnay field is required.")]
        public string CompanyName { get; set; }
        [Required(ErrorMessage = "Job type field is requied.")]
        public string JobType { get; set; }

        [Required(ErrorMessage = "Email field is required")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Address field is required")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Country field is empty.")]
        public string Country { get; set; }
        [Required(ErrorMessage = "State field is empty.")]
        public string State { get; set; }
        [Required(ErrorMessage = "Job Post date is empty.")]
        public string PostedDate { get; set; }
        [DisplayName("Require no. of Employees")]
        [Required(ErrorMessage = "Empty Job position field")]
        public Nullable<int> Vacancy { get; set; }
        [Required(ErrorMessage = "Job Nature field is empty.")]
        public string JobNature { get; set; }
    }
}
